name: Documentation CD
on:
    push:
        paths:
            - 'docs/**'
        branches: [main]

    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Begin CD...
              uses: actions/checkout@v2

            - name: Use Node 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Install deps and build (with cache) for base package
              uses: bahmutov/npm-install@v1

            - name: Building base package
              run: npm run build

            - name: Install deps and build (with cache)
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: ./packages/docs

            - name: Generating API documentation
              run: npm run docs:gen

            - name: Generating page indexes
              working-directory: ./packages/docs
              run: npm run generate:page-indexes

            - name: Building
              run: npm run build
              working-directory: ./packages/docs

            - name: Exporting
              run: npm run export
              working-directory: ./packages/docs

            - name: Publishing to github-pages
              run: |
                  git config --global user.name $user_name
                  git config --global user.email $user_email
                  git remote set-url origin https://${github_token}@github.com/${repository}
                  npm run push-gh-pages
              working-directory: ./packages/docs
              env:
                  user_name: 'github-actions[bot]'
                  user_email: 'github-actions[bot]@users.noreply.github.com'
                  github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
                  repository: ${{ github.repository }}
                  NODE_ENV: 'production'
