name: Documentation CI
on:
    pull_request:
        paths:
            - 'packages/docs/**'
        branches: [master]

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - name: Begin CI...
              uses: actions/checkout@v2

            - name: Use Node 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Install npm 17.x
              run: npm i -g npm@latest

            - name: Installing dependencies for base package
              run: npm ci

            - name: Building base package
              run: npm run build

            - name: Installing dependencies
              run: npm i

            - name: Building
              run: npm run build
              working-directory: ./packages/docs
